# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lehigh
tagline:          Beamer Themes
description:      'Beamer themes using Lehigh&#39;s colors'
url:              http://www.alexpacheco.us/
baseurl:          LehighBeamer/

author:
  name:           'Alex Pacheco'
  url:            http://www.alexpacheco.us

#paginate:         

# Custom vars
version:          

github:
  repo:           https://github.com/alexpacheco/LehighBeamer
  home:           htps://github.com/alexpacheco
