# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Lehigh
tagline:          Beamer Themes
description:      'Beamer themes using Lehigh&#39;s colors'
url:              http://www.alexpacheco.net/
baseurl:          LehighBeamer/

author:
  name:           'Alex Pacheco'
  url:            http://www.alexpacheco.net

#paginate:         

# Custom vars
version:          

github:
  repo:           https://github.com/alexpacheco/LehighBeamer
  home:           htps://github.com/alexpacheco
