# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lehigh Beamer Themes
tagline:          
description:      'Beamer themes for presentations using Lehigh&#39;s colors'
url:              http://www.alexpacheco.us/LehighBeamer
baseurl:          /

author:
  name:           'Alex Pacheco'
  url:            http://www.alexpacheco.us

paginate:         

# Custom vars
version:          

github:
  repo:           https://github.com/alexpacheco/LehighBeamer
  home:           htps://github.com/alexpacheci
